# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
processors:
  batch/metrics:
    timeout: 10s
    send_batch_size: 512
    send_batch_max_size: 1024
  batch/traces:
    timeout: 10s
    send_batch_size: 512
    send_batch_max_size: 1024

extensions:
  health_check: {}
exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:9090
    namespace: rest_app
  debug:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch/traces]
      exporters: [otlp, debug]

    metrics:
      receivers: [otlp]
      processors: [batch/metrics]
      exporters: [prometheus, debug]