# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:9090']

  - job_name: 'rest-skeleton'
    static_configs:
      - targets: ['host.docker.internal:8081'] 