name: Deploy Docker Image

on:
  pull_request:
    branches:
      - main
    types: [closed] # Trigger hanya saat PR di-merge

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull your-dockerhub-username/your-image-name:${{ github.sha }}
            docker rm -f your-container-name || true
            docker run -d --name your-container-name \
              -e APP_NAME=skeleton \
              -e APP_HOST=http://localhost \
              -e APP_PORT=8081 \
              -e APP_ENV=production \
              -e OTEL_COLLECTOR_ENDPOINT=localhost:4317 \
              -e LOKI_URL=http://localhost:3100/loki/api/v1/push \
              -e POSTGRES_HOST=localhost \
              -e POSTGRES_PORT=5432 \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_PASSWORD=1234 \
              -e POSTGRES_DB=simple_api \
              -e REDIS_HOST=localhost:6379 \
              -e REDIS_PASSWORD= \
              -e TOKEN_SALT=secret-security-salt \
              -e CONCURRENCY_LIMIT=5 \
              -e RATE_LIMIT_RPS=100 \
              -e RATE_LIMIT_BURST=2 \
              your-dockerhub-username/your-image-name:${{ github.sha }}